import { redirect } from "next/navigation";
import Link from "next/link";
import { Radar, Sparkles } from "lucide-react";
import { listDeals } from "@/lib/data/deals";
import { getAnalytics } from "@/lib/data/analytics";
import { countFollowUpsDue } from "@/lib/data/follow-ups";
import { isDbReady } from "@/lib/data/db";
import { hasAnyMarket } from "@/lib/data/markets";
import { readBriefing } from "@/lib/data/briefing-store";
import { RevenueKpis } from "@/components/dashboard/revenue-kpis";
import { KpiRow } from "@/components/dashboard/kpi-row";
import { PipelineSnapshot } from "@/components/dashboard/pipeline-snapshot";
import { DealCard } from "@/components/deals/deal-card";
import { StageBadge } from "@/components/deals/stage-badge";
import { CallButton } from "@/components/deals/call-button";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { formatCurrency } from "@/lib/utils";
import type { StageKey } from "@/constants/config";

export const dynamic = "force-dynamic";
export const metadata = { title: "Dashboard" };

export default async function DashboardPage() {
  // First-run check: if DB is up and no markets configured yet → onboarding
  if (await isDbReady()) {
    const onboarded = await hasAnyMarket();
    if (!onboarded) redirect("/onboarding");
  }

  const deals = await listDeals();
  const analytics = await getAnalytics();
  const followUpsDue = await countFollowUpsDue();
  const active = deals.filter((d) => d.stage !== "DEAD");
  const hot = deals.filter((d) => d.hot);
  const found = deals.filter((d) => d.stage === "FOUND");
  const totalSpread = active.reduce((s, d) => s + (d.profit ?? 0), 0);

  const counts: Partial<Record<StageKey, number>> = {};
  for (const d of deals) {
    counts[d.stage as StageKey] = (counts[d.stage as StageKey] ?? 0) + 1;
  }

  const topDeal = [...active].sort((a, b) => (b.score ?? 0) - (a.score ?? 0))[0];

  // Use stored AI briefing when available (generated by 8am cron), else fallback
  const storedBriefing = readBriefing();
  const insight = storedBriefing?.text ?? (topDeal
    ? `Your best opportunity right now is ${topDeal.address} — a ${topDeal.score}/100 lead with an estimated ${formatCurrency(topDeal.profit)} spread. Make the first move today.`
    : found.length > 0
      ? `${found.length} new ${found.length === 1 ? "deal" : "deals"} waiting to be contacted. Start the outreach.`
      : "No deals yet — run a scan to find your next opportunity.");

  const dateLabel = new Intl.DateTimeFormat("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
  }).format(new Date());

  const stats = [
    { label: "Active deals", value: String(active.length), tone: "info" as const },
    { label: "Hot leads", value: String(hot.length), tone: "brand" as const },
    {
      label: "Follow-ups due",
      value: String(followUpsDue),
      tone: "warning" as const,
    },
    {
      label: "Pipeline spread",
      value: formatCurrency(totalSpread, { compact: true }),
      tone: "brand" as const,
    },
  ];

  const attention = [
    ...hot,
    ...found.filter((d) => !hot.some((h) => h.id === d.id)),
  ].slice(0, 4);

  return (
    <div className="space-y-8">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h1 className="font-heading text-3xl tracking-wide sm:text-4xl">
            Good morning.
          </h1>
          <p className="text-sm text-muted-foreground">{dateLabel}</p>
        </div>
        <Button asChild variant="brand">
          <Link href="/find">
            <Radar className="h-4 w-4" /> Run a scan
          </Link>
        </Button>
      </div>

      {deals.length === 0 ? (
        <Card className="flex flex-col items-center gap-3 p-12 text-center">
          <div className="grid h-12 w-12 place-items-center rounded-xl bg-primary/15 text-primary shadow-glow-sm">
            <Radar className="h-6 w-6" />
          </div>
          <h2 className="font-heading text-2xl tracking-wide">
            Your pipeline is empty
          </h2>
          <p className="max-w-md text-sm text-muted-foreground">
            Scan a market to find motivated-seller deals, score them with AI, and
            start your pipeline. Everything you add is saved to your database.
          </p>
          <Button asChild variant="brand" className="mt-2">
            <Link href="/find">
              <Radar className="h-4 w-4" /> Find your first deals
            </Link>
          </Button>
        </Card>
      ) : (
        <>
          <Card className="flex items-start gap-3 border-primary/30 p-5 sm:p-6">
            <div className="grid h-10 w-10 shrink-0 place-items-center rounded-lg bg-primary/15 text-primary shadow-glow-sm">
              <Sparkles className="h-5 w-5" />
            </div>
            <div>
              <div className="text-xs font-semibold uppercase tracking-wider text-primary">
                Today&apos;s focus
              </div>
              <p className="mt-1 text-[15px] leading-relaxed">{insight}</p>
            </div>
          </Card>

          <KpiRow stats={stats} />

          <div>
            <h2 className="mb-3 font-heading text-xl tracking-wide">Revenue &amp; Conversion</h2>
            <RevenueKpis a={analytics} />
          </div>

          <div className="grid gap-6 lg:grid-cols-3">
            <div className="lg:col-span-2">
              <div className="mb-3 flex items-center justify-between">
                <h2 className="font-heading text-xl tracking-wide">
                  Needs your attention
                </h2>
                <Link href="/deals" className="text-xs text-primary hover:underline">
                  Full pipeline
                </Link>
              </div>
              {attention.length === 0 ? (
                <Card className="p-6 text-center text-sm text-muted-foreground">
                  Nothing urgent. Nice and calm.
                </Card>
              ) : (
                <div className="grid gap-4 sm:grid-cols-2">
                  {attention.map((deal) => (
                    <DealCard
                      key={deal.id}
                      deal={deal}
                      footer={
                        <div className="flex items-center gap-2">
                          <StageBadge stage={deal.stage} />
                          {deal.ownerPhone && (
                            <CallButton
                              deal={{
                                id: deal.id,
                                address: deal.address,
                                ownerName: deal.ownerName,
                                ownerPhone: deal.ownerPhone,
                              }}
                              variant="brand"
                            />
                          )}
                          <Button asChild variant="ghost" size="sm" className="ml-auto">
                            <Link href={`/deals/${deal.id}`}>Open</Link>
                          </Button>
                        </div>
                      }
                    />
                  ))}
                </div>
              )}
            </div>

            <div className="lg:col-span-1">
              <PipelineSnapshot counts={counts} />
            </div>
          </div>
        </>
      )}
    </div>
  );
}
